stages:
  prepare:
    cmd: python prepare.py data/raw/train_data.csv
    deps:
    - data/raw/train_data.csv
    - prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  train:
    cmd: python train.py data/prepared data/models/model.pkl
    deps:
    - data/prepared
    - train.py
    params:
    - train.C
    - train.features.max_features
    - train.features.ngrams
    - train.kernel
    outs:
    - data/models/model.pkl
