stages:
  prepare:
    cmd: python prepare.py data/raw/train_data.csv
    deps:
    - data/raw/train_data.csv
    - prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  train:
    cmd: python train.py data/prepared data/models/model.pkl
    deps:
    - data/prepared
    - train.py
    params:
    - train.C
    - train.features.max_features
    - train.features.ngrams
    - train.kernel
    outs:
    - data/models/model.pkl
  evaluate:
    cmd: python evaluate.py data/models/model.pkl data/prepared
    deps:
    - data/models/model.pkl
    - data/prepared
    - evaluate.py
    metrics:
    - data/metrics/scores.json:
        cache: false
    plots:
    - data/metrics/prc.json:
        cache: false
        x: recall
        y: precision
    - data/metrics/roc.json:
        cache: false
        x: fpr
        y: tpr
